favourite:
  drink: coffee
  food: pizza

pizzaToppings:
  - mushrooms
  - cheese
  - peppers
  - onions
  - pineapple

tlsSecrets:
  - name: tls-roywong-work
    certificate: certificate
    key: key
