---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-distributor-sa
  namespace: kube-system


---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-distributor-leader
  namespace: kube-system
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get","list","watch","create","update","patch"]
  - apiGroups: [""]
    resources: ["namespaces","secrets"]
    verbs: ["get","list","watch","create","update","patch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-distributor-binding
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: secret-distributor-sa
    namespace: kube-system
roleRef:
  kind: Role
  name: secret-distributor-leader
  apiGroup: rbac.authorization.k8s.io


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-credentials-distributor
  namespace: kube-system
  labels:
    app: docker-credentials-distributor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-credentials-distributor
  template:
    metadata:
      labels:
        app: docker-credentials-distributor
    spec:
      serviceAccountName: secret-distributor-sa
      containers:
        - name: distributor
          image: harbor.idc.roywong.work/library/docker-credentials-distributor:latest
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: config
              mountPath: /etc/docker-credentials.yaml
              subPath: docker-credentials.yaml
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: docker-credentials.yaml
            items:
              - key: docker-credentials.yaml
                path: docker-credentials.yaml