apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-credentials-distributor
  namespace: kube-system
  labels:
    app: docker-credentials-distributor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-credentials-distributor
  template:
    metadata:
      labels:
        app: docker-credentials-distributor
    spec:
      containers:
        - name: distributor
          image: harbor.idc.roywong.work/library/docker-credentials-distributor:latest
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: config
              mountPath: /etc/docker-credentials.yaml
              subPath: docker-credentials.yaml
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: docker-credentials.yaml
            items:
              - key: docker-credentials.yaml
                path: docker-credentials.yaml