---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-distributor-sa
  namespace: kube-system


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-distributor-role
rules:
  # Leader Election 用的 Lease
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get","list","watch","create","update","patch"]
  # 列 Namespace
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","list","watch"]
  # CRUD Secret
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","list","watch","create","update","patch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-distributor-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-distributor-role
subjects:
  - kind: ServiceAccount
    name: secret-distributor-sa
    namespace: kube-system


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-credentials-distributor
  namespace: kube-system
  labels:
    app: docker-credentials-distributor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-credentials-distributor
  template:
    metadata:
      labels:
        app: docker-credentials-distributor
    spec:
      serviceAccountName: secret-distributor-sa
      #imagePullSecrets:
      #  - name: registry-idc-library
      containers:
        - name: distributor
          image: harbor.idc.roywong.work/public/docker-credentials-distributor:latest
          env:
            - name: POD_NAME  # 环境变量POD_NAME对应docker-credentials-distributor程序中的资源ID。
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE # 环境变量NAMESPACE对应docker-credentials-distributor程序中的NAMESPACE，定义这个锁在哪个NAMESPACE中。
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOCK_NAME # 环境变量LOCK_NAME定义锁名称，默认值为"secret-distributor-lock"，多个POD去抢锁。
              value: "secret-distributor-lock"
          volumeMounts:
            - name: config
              mountPath: /etc/docker-credentials.yaml
              subPath: docker-credentials.yaml
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: docker-credentials.yaml
            items:
              - key: docker-credentials.yaml
                path: docker-credentials.yaml