---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          # image: harbor.idc.roywong.work/docker.io/library/busybox:1.37.0-glibc
          image: harbor.idc.roywong.work/library/argocd-cmp-jsonnet:1.0
          command: ["sleep", "infinity"]
          imagePullPolicy: Always
