apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: 'global-alertmanager-configuration'
  namespace: monitoring
spec:
  route:
    receiver: email-notify
    groupBy: ['alertname']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
  receivers:
    - name: email-notify
      emailConfigs:
        - to: 'roy_wong_20210324@163.com'
          from: 'roy_wong_20210324@163.com'
          authUsername: 'roy_wong_20210324@163.com'
          authPassword:
            name: email-password
            key: password
          authIdentity: 'roy_wong_20210324@163.com'
          requireTLS: true
          sendResolved: true
          smarthost: 'smtp.163.com'
