apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-config
  namespace: jenkins
data:
  config.json: |-
    {
            "auths": {
                    "harbor.idc.roywong.work": {
                            "auth": "YWRtaW46cStxOHR5SWxvUTNwcG9weXp2"
                    }
            }
    }
