apiVersion: v1
kind: ConfigMap
metadata:
  name: maven-settings
  namespace: jenkins
data:
  settings.xml: |-
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 
                                  https://maven.apache.org/xsd/settings-1.0.0.xsd">
    
      <mirrors>
        <mirror>
          <id>aliyun-public</id>
          <mirrorOf>*</mirrorOf>
          <name>Aliyun Maven Public Mirror</name>
          <url>https://maven.aliyun.com/repository/public</url>
        </mirror>
      </mirrors>
    
    </settings>
