---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-jenkins-workspace
  namespace: jenkins
  labels:
    app: data-jenkins-workspace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: infra