---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-maven-jdk8-workspace
  namespace: jenkins
  labels:
    app: data-maven-jdk8-workspace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: infra