---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-jenkins
  namespace: jenkins
  labels:
    app: data-jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: infra