apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 引用上一级的 base
resources:
  - ../../_bases/ingress

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: www
    path: patch-ingress.yaml