apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3     # 将副本数从 1 调整为 3
  template:
    spec:
      containers:
        - name: nginx
          image: harbor.idc.roywong.work/docker.io/nginx@sha256:596c783ac62b9a43c60edb876fe807376cd5022a4e25e89b9a9ae06c374299d4  # 替换成 app-1 所需的版本
          env:
            - name: ENV
              value: "production"
