apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: www
spec:
  ingressClassName: ingress-nginx-lan
  rules:
    - host: www.idc-ingress-nginx-lan.roywong.work
      http:
        paths:
          - backend:
              service:
                name: nginx
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - '*.idc-ingress-nginx-lan.roywong.work'
      secretName: roywong-work-tls-cert