apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3     # 将副本数从 1 调整为 3
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:1.18.0  # 替换成 app-1 所需的版本
          env:
            - name: ENV
              value: "production"
