apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"

  {{- $relname := .Release.Name -}}
  {{- with .Values.favourite }}
  drink: "{{ .drink | default "tea" }}"
  food: "{{ .food | upper }}"
  release: "{{ $relname }}"
  {{- end }}

  toppings: |-
    {{- range $index, $topping := .Values.pizzaToppings }}
    {{ $index }}: {{ $topping }}
    {{- end }}



# helm template clunky-serval ./java
# helm template clunky-serval ./java  --set favouriteDrink=slurm