apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ .Values.favourite.drink | repeat 5 |  quote }}
  food: {{ .Values.favourite.food | upper | quote }}


# helm template clunky-serval ./java
# helm template clunky-serval ./java  --set favouriteDrink=slurm