apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: "{{ .Values.favourite.drink | default "tea" }}"
  food: "{{ .Values.favourite.food | upper }}"
{{- if eq .Values.favourite.drink "coffee" }}
{{ indent 2 "mug: true" }}
{{- end }}


# helm template clunky-serval ./java
# helm template clunky-serval ./java  --set favouriteDrink=slurm