apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  {{- with .Values.favourite }}
  drink: "{{ .drink | default "tea" }}"
  food: "{{ .food | upper }}"
  {{- end }}


# helm template clunky-serval ./java
# helm template clunky-serval ./java  --set favouriteDrink=slurm