apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: "{{ .Values.favourite.drink }}"
  food: "{{ .Values.favourite.food }}"


# helm template clunky-serval ./java
# helm template clunky-serval ./java  --set favouriteDrink=slurm